### ISSUE TITLE
App not running (command line) "phonegap serve"

### ISSUE THREAD

**Issue by renatogalvones** [evothings/phonegap-estimotebeacons#42]
Don't know if it's possible, but I'm trying to run a "estimotetest" using the "phonegap serve" command.

This is supposed to work or will work just if I use Xcode?

Thanks a lot and congratz on the plugin.

**Comment by rblakeley** [comment]
How is PhoneGap a part of this project? It seems like Cordova is being used but not PhoneGap.

**Comment by fredrikeldh** [comment]
Cordova and PhoneGap are essentially the same thing, just with different names.

**Comment by rblakeley** [comment]
@fredrikeldh They are similar but not the exact same. It just seems misleading and confusing to name it "phonegap-..." if it's really "cordova-...". Is there a good reason why it has that name?

**Comment by fredrikeldh** [comment]
This is going to take a while. :}

First, see wikipedia: https://en.wikipedia.org/wiki/Apache_Cordova

PhoneGap is the original name of the software in question. When it was aquired by Adobe, the open-source part was donated to the Apache foundation, which, in order to avoid trademark infringement, renamed it "Cordova".

Now, as far as plugins are concerned, the two projects are equivalent; a PhoneGap plugin works in Cordova, and a Cordova plugin works in PhoneGap.

Plugins may be named for either project. Evothings prefers Cordova, so we name our plugins accordingly. phonegap-estimotebeacons, however, is not originally ours; we were given maintainership from the original author, [kdzwinel](https://github.com/kdzwinel). He's the one who named it, so I can only assume he preferred PhoneGap.

**Comment by rblakeley** [comment]
Thanks for the explanation.

**Comment by divineprog** [comment]
Closing this issue, let me know if to reopen.
